name: apply_stockbit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #* general project template
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  permission_handler: ^9.2.0
  riverpod: ^1.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  auto_route: ^4.0.1
  responsive_framework: ^0.2.0
  responsive_sizer: ^3.0.8
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #* general project template
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  flutter_gen: ^4.2.1
  flutter_gen_runner: ^4.2.1
  fast_i18n: ^5.12.6
  flutter_native_splash: ^2.2.2
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  #* general project template
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/env/.env.development
    - assets/env/.env.staging
    - assets/env/.env.production
    - assets/images/
    - assets/images/app_logo.png
  fonts:
    #* title font
    - family: Oranienbaum
      fonts:
        - asset: fonts/Oranienbaum/Oranienbaum-Regular.ttf
          weight: 400
    #* sub title font
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
    #* description font
    - family: Nunito Sans
      fonts:
        - asset: fonts/Nunito_Sans/NunitoSans-Regular.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-Italic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-Black.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-BlackItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-Bold.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-BoldItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraBold.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraBoldItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraLight.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraLightItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-Light.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-LightItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-Medium.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-MediumItalic.ttf
          style: italic
        - asset: fonts/Nunito_Sans/NunitoSans-SemiBold.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-SemiBoldItalic.ttf
          style: italic

#* general project template
flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/color_pallete.xml

flutter_native_splash:
  color: "#00BCD4"
  image: assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  adaptive_icon_background: "assets/images/app_logo_background.png"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"
